### PR TITLE
Update GitLab logo

### PR DESCRIPTION
**Pull request by kra-mo**
https://about.gitlab.com/press/

### CODE REVIEW

**Comment by razzeee** [comment]
You will need to convert this into a svg that react understands

**Comment by kra-mo** [comment]
Alright, done

**Comment by razzeee** [comment]
Doesn't seem right 
image

**Comment by kra-mo** [comment]
Okay, I really hope this will work now.

**Comment by razzeee** [comment]
Seems correct now, thanks

**Pull request merged**
