### PR TITLE
Add kabyle locale

### PR DESCRIPTION
**Pull request by gunchleoc**
Closes https://github.com/flathub-infra/website/issues/2708

Note that I don't know how to test this, I just grepped for `zh` and did my best. I can't learn a new codebase right now.

Kabyle language name translation taken from https://www.unicode.org/cldr/charts/44/summary/kab.html#787d4e0576d7869a

The flag is Algeria https://en.wikipedia.org/wiki/Kabyle_language

### CODE REVIEW

**Comment by razzeee** [comment]
These changes need to be done in addition, after translations become available

**Comment by BoFFire** [comment]
@razzeee Hi,

The problem is that I cannot translate in Kabyle : the file is empty. In Weblate it says 0 strings.

**Comment by razzeee** [comment]
Yeah, usually it sorts itself out somewhen

**Comment by BoFFire** [comment]
Wait and see

**Pull request closed without merging**
