### PR TITLE
utils: Ignore non-Linux screenshots

### PR DESCRIPTION
**Pull request by bbhtt**
Fixes https://github.com/flathub-infra/website/issues/4105

### CODE REVIEW

**Comment by bbhtt** [comment]
greenlet does not build with python 3.13

**Comment by bbhtt** [comment]
> I would prefer to not have `is_linux` exposed in the end, as it doesn't seem of much value?

Hm maybe I can expose `environment` instead directly.

**Comment by razzeee** [comment]
Should be good to go, optional things I can think of:

1. Omit null, when not set (save data on api requests)
2.  Have a test, that consumes macos/windows screenshots and check, if they are removed

**Comment by razzeee** [comment]
Thank you

**Pull request merged**
