### PR TITLE
Generate og images

### PR DESCRIPTION
**Pull request by razzeee**
Generate nicer og images on the fly - this only adds the generation, they are not used yet

image

This defaults to svg for now, as shadows seem broken with png - so we will need to revisit this.

https://github.com/flathub-infra/website/issues/2525

### CODE REVIEW

**Comment by razzeee** [comment]
Will wait for barth to return, as it's unclear how much performance this needs from the server and it would be nice to monitor it

**Comment by bertob** [comment]
A few notes based on the screenshot above:

- The logo in the bottom right needs more padding from the edges
- I'd make the title and subtitle a bit larger and reduce the spacing between them
- Ideally I'd make the icon larger as well, but IIRC we discussed this already and the problem was that we can't get a larger asset?

**Comment by razzeee** [comment]
Latest looks like this

image

**Comment by razzeee** [comment]
image

**Comment by razzeee** [comment]
Adjusted logo padding to the right

image

**Comment by razzeee** [comment]
Case without brand color and mobile screenshot

image

**Comment by bertob** [comment]
Vertical spacing looks good now, but I'd bump horizontal spacing a bit to match vertical. Something like 2x the current value should work.

**Pull request merged**
