### PR TITLE
Make titles use consistent case on home page

### PR DESCRIPTION
**Pull request by kra-mo**

### CODE REVIEW

**Comment by razzeee** [comment]
Please only change the en.json

I would also prefer to have the categories changed instead of the strings you touched now.

**Comment by kra-mo** [comment]
What do you mean by "the categories"?

**Comment by kra-mo** [comment]
Yeah, would you change the appstream ones to not be title case then?

**Comment by kra-mo** [comment]
That just wouldn't look very good because of the &'s separating what are two identically weighted categories.

image

**Comment by kra-mo** [comment]
Okay, I have reverted en-GB

**Comment by razzeee** [comment]
Thank you.

Personally I would prefer the other way around, but as the main headline is using the same casing, whatever :)

The home page will hopefully see a rework soonish anyway.

**Pull request merged**
